# Tratando dados sting para ML

Usaremos duas tecnicas para isso.

-dummys
-one hot enconding

In [1]:
%pip install openpyxl -q
%pip install scikit-learn -q

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pandas-profiling 3.2.0 requires joblib~=1.1.0, but you have joblib 1.5.0 which is incompatible.

In [2]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

df = pd.read_excel('dados.xlsx')

In [3]:
df.shape

(986, 7)

In [4]:
df.head()

,MODELO,KM-LITRO,CILINDROS,PESO(KG),CAVALOS,TRANSMISSAO,PAIS
0,LABORGUINI,3.0,12,1200,700,AUTOMATICO,BRASIL
1,LABORGUINI,3.0,12,1200,700,AUTOMATICO,EUA
2,LABORGUINI,3.0,12,1200,700,AUTOMATICO,ESPANHA
3,FERRARI,3.0,12,1400,640,AUTOMATICO,CANADA
4,ASTON MARTIN,3.5,10,1600,620,AUTOMATICO,INGLATERRA

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986 entries, 0 to 985
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MODELO       986 non-null    object
 1   KM-LITRO     984 non-null    float64
 2   CILINDROS    986 non-null    int64
 3   PESO(KG)     986 non-null    int64
 4   CAVALOS      986 non-null    int64
 5   TRANSMISSAO  986 non-null    object
 6   PAIS         986 non-null    object
dtypes: float64(1), int64(3), object(3)
memory usage: 54.1+ KB

In [6]:
df['PAIS'].value_counts

<bound method IndexOpsMixin.value_counts of 0          BRASIL
1             EUA
2         ESPANHA
3          CANADA
4      INGLATERRA
5        ALEMANHA
6       AUSTRALIA
7         NORUEGA
8         BELGICA
9         HOLANDA
10         BRASIL
11            EUA
12        ESPANHA
13         CANADA
14     INGLATERRA
15       ALEMANHA
16      AUSTRALIA
17        NORUEGA
18        BELGICA
19        HOLANDA
20         BRASIL
21            EUA
22        ESPANHA
23         CANADA
24     INGLATERRA
25       ALEMANHA
26      AUSTRALIA
27        NORUEGA
28        BELGICA
29        HOLANDA
30         BRASIL
31            EUA
32        ESPANHA
33         CANADA
34     INGLATERRA
35       ALEMANHA
36      AUSTRALIA
37        NORUEGA
38        BELGICA
39        HOLANDA
40         BRASIL
41            EUA
42        ESPANHA
43         CANADA
44     INGLATERRA
45       ALEMANHA
46      AUSTRALIA
47        NORUEGA
48        BELGICA
49        HOLANDA
50         BRASIL
51            EUA
52        ESPANHA
53         CANADA
54     INGLATERRA
55       ALEMANHA
56      AUSTRALIA
57        NORUEGA
58        BELGICA
59        HOLANDA
60         BRASIL
61            EUA
62        ESPANHA
63         CANADA
64     INGLATERRA
65       ALEMANHA
66      AUSTRALIA
67        NORUEGA
68        BELGICA
69        HOLANDA
70         BRASIL
71            EUA
72        ESPANHA
73         CANADA
74     INGLATERRA
75       ALEMANHA
76      AUSTRALIA
77        NORUEGA
78        BELGICA
79        HOLANDA
80         BRASIL
81            EUA
82        ESPANHA
83         CANADA
84     INGLATERRA
85       ALEMANHA
86      AUSTRALIA
87        NORUEGA
88        BELGICA
89        HOLANDA
90         BRASIL
91            EUA
92        ESPANHA
93         CANADA
94     INGLATERRA
95       ALEMANHA
96      AUSTRALIA
97        NORUEGA
98        BELGICA
99        HOLANDA
100        BRASIL
101           EUA
102       ESPANHA
103        CANADA
104    INGLATERRA
105      ALEMANHA
106     AUSTRALIA
107       NORUEGA
108       BELGICA
109       HOLANDA
110        BRASIL
111           EUA
112       ESPANHA
113        CANADA
114    INGLATERRA
115      ALEMANHA
116     AUSTRALIA
117       NORUEGA
118       BELGICA
119       HOLANDA
120        BRASIL
121           EUA
122       ESPANHA
123        CANADA
124    INGLATERRA
125      ALEMANHA
126     AUSTRALIA
127       NORUEGA
128       BELGICA
129       HOLANDA
130        BRASIL
131           EUA
132       ESPANHA
133        CANADA
134    INGLATERRA
135      ALEMANHA
136     AUSTRALIA
137       NORUEGA
138       BELGICA
139       HOLANDA
140        BRASIL
141           EUA
142       ESPANHA
143        CANADA
144    INGLATERRA
145      ALEMANHA
146     AUSTRALIA
147       NORUEGA
148       BELGICA
149       HOLANDA
150        BRASIL
151           EUA
152       ESPANHA
153        CANADA
154    INGLATERRA
155      ALEMANHA
156     AUSTRALIA
157       NORUEGA
158       BELGICA
159       HOLANDA
160        BRASIL
161           EUA
162       ESPANHA
163        CANADA
164    INGLATERRA
165      ALEMANHA
166     AUSTRALIA
167       NORUEGA
168       BELGICA
169       HOLANDA
170        BRASIL
171           EUA
172       ESPANHA
173        CANADA
174    INGLATERRA
175      ALEMANHA
176     AUSTRALIA
177       NORUEGA
178       BELGICA
179       HOLANDA
180        BRASIL
181           EUA
182       ESPANHA
183        CANADA
184    INGLATERRA
185      ALEMANHA
186     AUSTRALIA
187       NORUEGA
188       BELGICA
189       HOLANDA
190        BRASIL
191           EUA
192       ESPANHA
193        CANADA
194    INGLATERRA
195      ALEMANHA
196     AUSTRALIA
197       NORUEGA
198       BELGICA
199       HOLANDA
200        BRASIL
201           EUA
202       ESPANHA
203        CANADA
204    INGLATERRA
205      ALEMANHA
206     AUSTRALIA
207       NORUEGA
208       BELGICA
209       HOLANDA
210        BRASIL
211           EUA
212       ESPANHA
213        CANADA
214    INGLATERRA
215      ALEMANHA
216     AUSTRALIA
217       NORUEGA
218       BELGICA
219       HOLANDA
220        BRASIL
221           EUA
222       ESPANHA
223        CANADA
224    INGLATERRA
225      ALEMANHA
226     AUSTRALIA
227       NORUEGA
228       BELGICA
229       HOLANDA
230        BRASIL
231           EUA
232       ESPANHA
233        CANADA
234    INGLATERRA
235      ALEMANHA
236     AUSTRALIA
237       NORUEGA
238       BELGICA
239       HOLANDA
240        BRASIL
241           EUA
242       ESPANHA
243        CANADA
244    INGLATERRA
245      ALEMANHA
246     AUSTRALIA
247       NORUEGA
248       BELGICA
249       HOLANDA
250        BRASIL
251           EUA
252       ESPANHA
253        CANADA
254    INGLATERRA
255      ALEMANHA
256     AUSTRALIA
257       NORUEGA
258       BELGICA
259       HOLANDA
260        BRASIL
261           EUA
262       ESPANHA
263        CANADA
264    INGLATERRA
265      ALEMANHA
266     AUSTRALIA
267       NORUEGA
268       BELGICA
269       HOLANDA
270        BRASIL
271           EUA
272       ESPANHA
273        CANADA
274    INGLATERRA
275      ALEMANHA
276     AUSTRALIA
277       NORUEGA
278       BELGICA
279       HOLANDA
280        BRASIL
281           EUA
282       ESPANHA
283        CANADA
284    INGLATERRA
285      ALEMANHA
286     AUSTRALIA
287       NORUEGA
288       BELGICA
289       HOLANDA
290        BRASIL
291           EUA
292       ESPANHA
293        CANADA
294    INGLATERRA
295      ALEMANHA
296     AUSTRALIA
297       NORUEGA
298       BELGICA
299       HOLANDA
300        BRASIL
301           EUA
302       ESPANHA
303        CANADA
304    INGLATERRA
305      ALEMANHA
306     AUSTRALIA
307       NORUEGA
308       BELGICA
309       HOLANDA
310        BRASIL
311           EUA
312       ESPANHA
313        CANADA
314    INGLATERRA
315      ALEMANHA
316     AUSTRALIA
317       NORUEGA
318       BELGICA
319       HOLANDA
320        BRASIL
321           EUA
322       ESPANHA
323        CANADA
324    INGLATERRA
325      ALEMANHA
326     AUSTRALIA
327       NORUEGA
328       BELGICA
329       HOLANDA
330        BRASIL
331           EUA
332       ESPANHA
333        CANADA
334    INGLATERRA
335      ALEMANHA
336     AUSTRALIA
337       NORUEGA
338       BELGICA
339       HOLANDA
340        BRASIL
341           EUA
342       ESPANHA
343        CANADA
344    INGLATERRA
345      ALEMANHA
346     AUSTRALIA
347       NORUEGA
348       BELGICA
349       HOLANDA
350        BRASIL
351           EUA
352       ESPANHA
353        CANADA
354    INGLATERRA
355      ALEMANHA
356     AUSTRALIA
357       NORUEGA
358       BELGICA
359       HOLANDA
360        BRASIL
361           EUA
362       ESPANHA
363        CANADA
364    INGLATERRA
365      ALEMANHA
366     AUSTRALIA
367       NORUEGA
368       BELGICA
369       HOLANDA
370        BRASIL
371           EUA
372       ESPANHA
373        CANADA
374    INGLATERRA
375      ALEMANHA
376     AUSTRALIA
377       NORUEGA
378       BELGICA
379       HOLANDA
380        BRASIL
381           EUA
382       ESPANHA
383        CANADA
384    INGLATERRA
385      ALEMANHA
386     AUSTRALIA
387       NORUEGA
388       BELGICA
389       HOLANDA
390        BRASIL
391           EUA
392       ESPANHA
393        CANADA
394    INGLATERRA
395      ALEMANHA
396     AUSTRALIA
397       NORUEGA
398       BELGICA
399       HOLANDA
400        BRASIL
401           EUA
402       ESPANHA
403        CANADA
404    INGLATERRA
405      ALEMANHA
406     AUSTRALIA
407       NORUEGA
408       BELGICA
409       HOLANDA
410        BRASIL
411           EUA
412       ESPANHA
413        CANADA
414    INGLATERRA
415      ALEMANHA
416     AUSTRALIA
417       NORUEGA
418       BELGICA
419       HOLANDA
420        BRASIL
421           EUA
422       ESPANHA
423        CANADA
424    INGLATERRA
425      ALEMANHA
426     AUSTRALIA
427       NORUEGA
428       BELGICA
429       HOLANDA
430        BRASIL
431           EUA
432       ESPANHA
433        CANADA
434    INGLATERRA
435      ALEMANHA
436     AUSTRALIA
437       NORUEGA
438       BELGICA
439       HOLANDA
440        BRASIL
441           EUA
442       ESPANHA
443        CANADA
444    INGLATERRA
445      ALEMANHA
446     AUSTRALIA
447       NORUEGA
448       BELGICA
449       HOLANDA
450        BRASIL
451           EUA
452       ESPANHA
453        CANADA
454    INGLATERRA
455      ALEMANHA
456     AUSTRALIA
457       NORUEGA
458       BELGICA
459       HOLANDA
460        BRASIL
461           EUA
462       ESPANHA
463        CANADA
464    INGLATERRA
465      ALEMANHA
466     AUSTRALIA
467       NORUEGA
468       BELGICA
469       HOLANDA
470        BRASIL
471           EUA
472       ESPANHA
473        CANADA
474    INGLATERRA
475      ALEMANHA
476     AUSTRALIA
477       NORUEGA
478       BELGICA
479       HOLANDA
480        BRASIL
481           EUA
482       ESPANHA
483        CANADA
484    INGLATERRA
485      ALEMANHA
486     AUSTRALIA
487       NORUEGA
488       BELGICA
489       HOLANDA
490        BRASIL
491           EUA
492       ESPANHA
493        CANADA
494    INGLATERRA
495      ALEMANHA
496     AUSTRALIA
497       NORUEGA
498       BELGICA
499       HOLANDA
500        BRASIL
501           EUA
502       ESPANHA
503        CANADA
504    INGLATERRA
505      ALEMANHA
506     AUSTRALIA
507       NORUEGA
508       BELGICA
509       HOLANDA
510        BRASIL
511           EUA
512       ESPANHA
513        CANADA
514    INGLATERRA
515      ALEMANHA
516     AUSTRALIA
517       NORUEGA
518       BELGICA
519       HOLANDA
520        BRASIL
521           EUA
522       ESPANHA
523        CANADA
524    INGLATERRA
525      ALEMANHA
526     AUSTRALIA
527       NORUEGA
528       BELGICA
529       HOLANDA
530        BRASIL
531           EUA
532       ESPANHA
533        CANADA
534    INGLATERRA
535      ALEMANHA
536     AUSTRALIA
537       NORUEGA
538       BELGICA
539       HOLANDA
540        BRASIL
541           EUA
542       ESPANHA
543        CANADA
544    INGLATERRA
545      ALEMANHA
546     AUSTRALIA
547       NORUEGA
548       BELGICA
549       HOLANDA
550        BRASIL
551           EUA
552       ESPANHA
553        CANADA
554    INGLATERRA
555      ALEMANHA
556     AUSTRALIA
557       NORUEGA
558       BELGICA
559       HOLANDA
560        BRASIL
561           EUA
562       ESPANHA
563        CANADA
564    INGLATERRA
565      ALEMANHA
566     AUSTRALIA
567       NORUEGA
568       BELGICA
569       HOLANDA
570        BRASIL
571           EUA
572       ESPANHA
573        CANADA
574    INGLATERRA
575      ALEMANHA
576     AUSTRALIA
577       NORUEGA
578       BELGICA
579       HOLANDA
580        BRASIL
581           EUA
582       ESPANHA
583        CANADA
584    INGLATERRA
585      ALEMANHA
586     AUSTRALIA
587       NORUEGA
588       BELGICA
589       HOLANDA
590        BRASIL
591           EUA
592       ESPANHA
593        CANADA
594    INGLATERRA
595      ALEMANHA
596     AUSTRALIA
597       NORUEGA
598       BELGICA
599       HOLANDA
600        BRASIL
601           EUA
602       ESPANHA
603        CANADA
604    INGLATERRA
605      ALEMANHA
606     AUSTRALIA
607       NORUEGA
608       BELGICA
609       HOLANDA
610        BRASIL
611           EUA
612       ESPANHA
613        CANADA
614    INGLATERRA
615      ALEMANHA
616     AUSTRALIA
617       NORUEGA
618       BELGICA
619       HOLANDA
620        BRASIL
621           EUA
622       ESPANHA
623        CANADA
624    INGLATERRA
625      ALEMANHA
626     AUSTRALIA
627       NORUEGA
628       BELGICA
629       HOLANDA
630        BRASIL
631           EUA
632       ESPANHA
633        CANADA
634    INGLATERRA
635      ALEMANHA
636     AUSTRALIA
637       NORUEGA
638       BELGICA
639       HOLANDA
640        BRASIL
641           EUA
642       ESPANHA
643        CANADA
644    INGLATERRA
645      ALEMANHA
646     AUSTRALIA
647       NORUEGA
648       BELGICA
649       HOLANDA
650        BRASIL
651           EUA
652       ESPANHA
653        CANADA
654    INGLATERRA
655      ALEMANHA
656     AUSTRALIA
657       NORUEGA
658       BELGICA
659       HOLANDA
660        BRASIL
661           EUA
662       ESPANHA
663        CANADA
664    INGLATERRA
665      ALEMANHA
666     AUSTRALIA
667       NORUEGA
668       BELGICA
669       HOLANDA
670        BRASIL
671           EUA
672       ESPANHA
673        CANADA
674    INGLATERRA
675      ALEMANHA
676     AUSTRALIA
677       NORUEGA
678       BELGICA
679       HOLANDA
680        BRASIL
681           EUA
682       ESPANHA
683        CANADA
684    INGLATERRA
685      ALEMANHA
686     AUSTRALIA
687       NORUEGA
688       BELGICA
689       HOLANDA
690        BRASIL
691           EUA
692       ESPANHA
693        CANADA
694    INGLATERRA
695      ALEMANHA
696     AUSTRALIA
697       NORUEGA
698       BELGICA
699       HOLANDA
700        BRASIL
701           EUA
702       ESPANHA
703        CANADA
704    INGLATERRA
705      ALEMANHA
706     AUSTRALIA
707       NORUEGA
708       BELGICA
709       HOLANDA
710        BRASIL
711           EUA
712       ESPANHA
713        CANADA
714    INGLATERRA
715      ALEMANHA
716     AUSTRALIA
717       NORUEGA
718       BELGICA
719       HOLANDA
720        BRASIL
721           EUA
722       ESPANHA
723        CANADA
724    INGLATERRA
725      ALEMANHA
726     AUSTRALIA
727       NORUEGA
728       BELGICA
729       HOLANDA
730        BRASIL
731           EUA
732       ESPANHA
733        CANADA
734    INGLATERRA
735      ALEMANHA
736     AUSTRALIA
737       NORUEGA
738       BELGICA
739       HOLANDA
740        BRASIL
741           EUA
742       ESPANHA
743        CANADA
744    INGLATERRA
745      ALEMANHA
746     AUSTRALIA
747       NORUEGA
748       BELGICA
749       HOLANDA
750        BRASIL
751           EUA
752       ESPANHA
753        CANADA
754    INGLATERRA
755      ALEMANHA
756     AUSTRALIA
757       NORUEGA
758       BELGICA
759       HOLANDA
760        BRASIL
761           EUA
762       ESPANHA
763        CANADA
764    INGLATERRA
765      ALEMANHA
766     AUSTRALIA
767       NORUEGA
768       BELGICA
769       HOLANDA
770        BRASIL
771           EUA
772       ESPANHA
773        CANADA
774    INGLATERRA
775      ALEMANHA
776     AUSTRALIA
777       NORUEGA
778       BELGICA
779       HOLANDA
780        BRASIL
781           EUA
782       ESPANHA
783        CANADA
784    INGLATERRA
785      ALEMANHA
786     AUSTRALIA
787       NORUEGA
788       BELGICA
789       HOLANDA
790        BRASIL
791           EUA
792       ESPANHA
793        CANADA
794    INGLATERRA
795      ALEMANHA
796     AUSTRALIA
797       NORUEGA
798       BELGICA
799       HOLANDA
800        BRASIL
801           EUA
802       ESPANHA
803        CANADA
804    INGLATERRA
805      ALEMANHA
806     AUSTRALIA
807       NORUEGA
808       BELGICA
809       HOLANDA
810        BRASIL
811           EUA
812       ESPANHA
813        CANADA
814    INGLATERRA
815      ALEMANHA
816     AUSTRALIA
817       NORUEGA
818       BELGICA
819       HOLANDA
820        BRASIL
821           EUA
822       ESPANHA
823        CANADA
824    INGLATERRA
825      ALEMANHA
826     AUSTRALIA
827       NORUEGA
828       BELGICA
829       HOLANDA
830        BRASIL
831           EUA
832       ESPANHA
833        CANADA
834    INGLATERRA
835      ALEMANHA
836     AUSTRALIA
837       NORUEGA
838       BELGICA
839       HOLANDA
840        BRASIL
841           EUA
842       ESPANHA
843        CANADA
844    INGLATERRA
845      ALEMANHA
846     AUSTRALIA
847       NORUEGA
848       BELGICA
849       HOLANDA
850        BRASIL
851           EUA
852       ESPANHA
853        CANADA
854    INGLATERRA
855      ALEMANHA
856     AUSTRALIA
857       NORUEGA
858       BELGICA
859       HOLANDA
860        BRASIL
861           EUA
862       ESPANHA
863        CANADA
864    INGLATERRA
865      ALEMANHA
866     AUSTRALIA
867       NORUEGA
868       BELGICA
869       HOLANDA
870        BRASIL
871           EUA
872       ESPANHA
873        CANADA
874    INGLATERRA
875      ALEMANHA
876     AUSTRALIA
877       NORUEGA
878       BELGICA
879       HOLANDA
880        BRASIL
881           EUA
882       ESPANHA
883        CANADA
884    INGLATERRA
885      ALEMANHA
886     AUSTRALIA
887       NORUEGA
888       BELGICA
889       HOLANDA
890        BRASIL
891           EUA
892       ESPANHA
893        CANADA
894    INGLATERRA
895      ALEMANHA
896     AUSTRALIA
897       NORUEGA
898       BELGICA
899       HOLANDA
900        BRASIL
901           EUA
902       ESPANHA
903        CANADA
904    INGLATERRA
905      ALEMANHA
906     AUSTRALIA
907       NORUEGA
908       BELGICA
909       HOLANDA
910        BRASIL
911           EUA
912       ESPANHA
913        CANADA
914    INGLATERRA
915      ALEMANHA
916     AUSTRALIA
917       NORUEGA
918       BELGICA
919       HOLANDA
920        BRASIL
921           EUA
922       ESPANHA
923        CANADA
924    INGLATERRA
925      ALEMANHA
926     AUSTRALIA
927       NORUEGA
928       BELGICA
929       HOLANDA
930        BRASIL
931           EUA
932       ESPANHA
933        CANADA
934    INGLATERRA
935      ALEMANHA
936     AUSTRALIA
937       NORUEGA
938       BELGICA
939       HOLANDA
940        BRASIL
941           EUA
942       ESPANHA
943        CANADA
944    INGLATERRA
945      ALEMANHA
946     AUSTRALIA
947       NORUEGA
948       BELGICA
949       HOLANDA
950        BRASIL
951           EUA
952       ESPANHA
953        CANADA
954    INGLATERRA
955      ALEMANHA
956     AUSTRALIA
957       NORUEGA
958       BELGICA
959       HOLANDA
960        BRASIL
961           EUA
962       ESPANHA
963        CANADA
964    INGLATERRA
965      ALEMANHA
966     AUSTRALIA
967       NORUEGA
968       BELGICA
969       HOLANDA
970        BRASIL
971           EUA
972       ESPANHA
973        CANADA
974    INGLATERRA
975      ALEMANHA
976     AUSTRALIA
977       NORUEGA
978       BELGICA
979       HOLANDA
980        BRASIL
981           EUA
982       ESPANHA
983        CANADA
984    INGLATERRA
985      ALEMANHA
Name: PAIS, dtype: object>

In [7]:
df['TRANSMISSAO'].value_counts()

TRANSMISSAO
AUTOMATICO    536
MANUAL        450
Name: count, dtype: int64

In [8]:
df['MODELO'].value_counts()

MODELO
MERCEDES SL80    66
ASTON MARTIN     66
HONDA FIT        66
PALIO            66
MOBI             66
UNO              66
PASSAT           66
FERRARI          54
LABORGUINI       50
CORSA            42
SAVEIRO          42
BMW X5           36
JEEP COMPASS     36
CRETA            36
PAJERO           36
COROLLA          36
HB20             30
BMW X1           30
JEEP RENEGADE    24
PARATI           24
GOL              24
VECTRA           24
Name: count, dtype: int64

# Metodo DUMMY

transforma as possibilidades de uma variavel categorica em uma serie binaria

In [9]:
df_dummy = pd.get_dummies(df)

In [10]:
df_dummy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986 entries, 0 to 985
Data columns (total 38 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   KM-LITRO                984 non-null    float64
 1   CILINDROS               986 non-null    int64
 2   PESO(KG)                986 non-null    int64
 3   CAVALOS                 986 non-null    int64
 4   MODELO_ASTON MARTIN     986 non-null    bool
 5   MODELO_BMW X1           986 non-null    bool
 6   MODELO_BMW X5           986 non-null    bool
 7   MODELO_COROLLA          986 non-null    bool
 8   MODELO_CORSA            986 non-null    bool
 9   MODELO_CRETA            986 non-null    bool
 10  MODELO_FERRARI          986 non-null    bool
 11  MODELO_GOL              986 non-null    bool
 12  MODELO_HB20             986 non-null    bool
 13  MODELO_HONDA FIT        986 non-null    bool
 14  MODELO_JEEP COMPASS     986 non-null    bool
 15  MODELO_JEEP RENEGADE    986 non-null    bool
 16  MODELO_LABORGUINI       986 non-null    bool
 17  MODELO_MERCEDES SL80    986 non-null    bool
 18  MODELO_MOBI             986 non-null    bool
 19  MODELO_PAJERO           986 non-null    bool
 20  MODELO_PALIO            986 non-null    bool
 21  MODELO_PARATI           986 non-null    bool
 22  MODELO_PASSAT           986 non-null    bool
 23  MODELO_SAVEIRO          986 non-null    bool
 24  MODELO_UNO              986 non-null    bool
 25  MODELO_VECTRA           986 non-null    bool
 26  TRANSMISSAO_AUTOMATICO  986 non-null    bool
 27  TRANSMISSAO_MANUAL      986 non-null    bool
 28  PAIS_ALEMANHA           986 non-null    bool
 29  PAIS_AUSTRALIA          986 non-null    bool
 30  PAIS_BELGICA            986 non-null    bool
 31  PAIS_BRASIL             986 non-null    bool
 32  PAIS_CANADA             986 non-null    bool
 33  PAIS_ESPANHA            986 non-null    bool
 34  PAIS_EUA                986 non-null    bool
 35  PAIS_HOLANDA            986 non-null    bool
 36  PAIS_INGLATERRA         986 non-null    bool
 37  PAIS_NORUEGA            986 non-null    bool
dtypes: bool(34), float64(1), int64(3)
memory usage: 63.7 KB

In [11]:
df_dummy.shape

(986, 38)

In [12]:
df_dummy.head()

,KM-LITRO,CILINDROS,PESO(KG),CAVALOS,MODELO_ASTON MARTIN,MODELO_BMW X1,MODELO_BMW X5,MODELO_COROLLA,MODELO_CORSA,MODELO_CRETA,MODELO_FERRARI,MODELO_GOL,MODELO_HB20,MODELO_HONDA FIT,MODELO_JEEP COMPASS,MODELO_JEEP RENEGADE,MODELO_LABORGUINI,MODELO_MERCEDES SL80,MODELO_MOBI,MODELO_PAJERO,MODELO_PALIO,MODELO_PARATI,MODELO_PASSAT,MODELO_SAVEIRO,MODELO_UNO,MODELO_VECTRA,TRANSMISSAO_AUTOMATICO,TRANSMISSAO_MANUAL,PAIS_ALEMANHA,PAIS_AUSTRALIA,PAIS_BELGICA,PAIS_BRASIL,PAIS_CANADA,PAIS_ESPANHA,PAIS_EUA,PAIS_HOLANDA,PAIS_INGLATERRA,PAIS_NORUEGA
0,3.0,12,1200,700,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False
1,3.0,12,1200,700,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False
2,3.0,12,1200,700,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False
3,3.0,12,1400,640,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False
4,3.5,10,1600,620,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False

In [13]:
df_dummy_transmissao =pd.get_dummies(df['TRANSMISSAO'])

df_completo = pd.concat([df, df_dummy_transmissao], axis=1)

df_completo.head()

,MODELO,KM-LITRO,CILINDROS,PESO(KG),CAVALOS,TRANSMISSAO,PAIS,AUTOMATICO,MANUAL
0,LABORGUINI,3.0,12,1200,700,AUTOMATICO,BRASIL,True,False
1,LABORGUINI,3.0,12,1200,700,AUTOMATICO,EUA,True,False
2,LABORGUINI,3.0,12,1200,700,AUTOMATICO,ESPANHA,True,False
3,FERRARI,3.0,12,1400,640,AUTOMATICO,CANADA,True,False
4,ASTON MARTIN,3.5,10,1600,620,AUTOMATICO,INGLATERRA,True,False

# Metodo One hot Encoding

usaremos o scikit-learn para esta tecnica

In [14]:
df =pd.read_excel('./dados.xlsx')
df.shape

(986, 7)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986 entries, 0 to 985
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MODELO       986 non-null    object
 1   KM-LITRO     984 non-null    float64
 2   CILINDROS    986 non-null    int64
 3   PESO(KG)     986 non-null    int64
 4   CAVALOS      986 non-null    int64
 5   TRANSMISSAO  986 non-null    object
 6   PAIS         986 non-null    object
dtypes: float64(1), int64(3), object(3)
memory usage: 54.1+ KB

In [16]:
df.head()

,MODELO,KM-LITRO,CILINDROS,PESO(KG),CAVALOS,TRANSMISSAO,PAIS
0,LABORGUINI,3.0,12,1200,700,AUTOMATICO,BRASIL
1,LABORGUINI,3.0,12,1200,700,AUTOMATICO,EUA
2,LABORGUINI,3.0,12,1200,700,AUTOMATICO,ESPANHA
3,FERRARI,3.0,12,1400,640,AUTOMATICO,CANADA
4,ASTON MARTIN,3.5,10,1600,620,AUTOMATICO,INGLATERRA

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
lb = LabelEncoder()

for serie in ['PAIS', 'TRANSMISSAO', 'MODELO']:
    df[serie] = lb.fit_transform(df[serie])

In [19]:
df.shape

(986, 7)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986 entries, 0 to 985
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MODELO       986 non-null    int64
 1   KM-LITRO     984 non-null    float64
 2   CILINDROS    986 non-null    int64
 3   PESO(KG)     986 non-null    int64
 4   CAVALOS      986 non-null    int64
 5   TRANSMISSAO  986 non-null    int64
 6   PAIS         986 non-null    int64
dtypes: float64(1), int64(6)
memory usage: 54.1 KB

In [21]:
df.head()

   MODELO  KM-LITRO  CILINDROS  PESO(KG)  CAVALOS  TRANSMISSAO  PAIS
0      12       3.0         12      1200      700            0     3
1      12       3.0         12      1200      700            0     6
2      12       3.0         12      1200      700            0     5
3       6       3.0         12      1400      640            0     4
4       0       3.5         10      1600      620            0     8

In [22]:
df['PAIS'].value_counts()

PAIS
3    99
6    99
5    99
4    99
8    99
0    99
1    98
9    98
2    98
7    98
Name: count, dtype: int64

In [23]:
df.groupby('PAIS').size()

PAIS
0    99
1    98
2    98
3    99
4    99
5    99
6    99
7    98
8    99
9    98
dtype: int64

In [24]:
df_dados = pd.read_excel('dados.xlsx')

legendas = {}

for var in ['PAIS', 'TRANSMISSAO', 'MODELO']:
    lb = LabelEncoder()  

    df_originais = df_dados[var].copy()

    # Fit and transform the data
    df_dados[var] = lb.fit_transform(df_originais)

    # Create a legend mapping
    legenda_var = dict(zip(lb.classes_, lb.transform(lb.classes_)))
    legendas[var] = legenda_var

# Print the legends
for var, mapa in legendas.items():
    print(f"\nLegenda para {var}:")
    for k, v in mapa.items():
        print(f" {k} : {v}")

Legenda para PAIS:
 ALEMANHA : 0
 AUSTRALIA : 1
 BELGICA : 2
 BRASIL : 3
 CANADA : 4
 ESPANHA : 5
 EUA : 6
 HOLANDA : 7
 INGLATERRA : 8
 NORUEGA : 9

Legenda para TRANSMISSAO:
 AUTOMATICO : 0
 MANUAL : 1

Legenda para MODELO:
 ASTON MARTIN : 0
 BMW X1 : 1
 BMW X5 : 2
 COROLLA : 3
 CORSA : 4
 CRETA : 5
 FERRARI : 6
 GOL : 7
 HB20 : 8
 HONDA FIT : 9
 JEEP COMPASS : 10
 JEEP RENEGADE : 11
 LABORGUINI : 12
 MERCEDES SL80 : 13
 MOBI : 14
 PAJERO : 15
 PALIO : 16
 PARATI : 17
 PASSAT : 18
 SAVEIRO : 19
 UNO : 20
 VECTRA : 21

In [25]:
paises = ['Argentina', 'Brasil', 'Chile']

lb2 = LabelEncoder()

lb2.fit_transform(paises)

print(lb2.classes_)

['Argentina' 'Brasil' 'Chile']

In [26]:
print(lb2.transform(lb2.classes_))

[0 1 2]

In [27]:
print(dict(zip(lb2.classes_,lb2.transform(lb2.classes_))))

{np.str_('Argentina'): np.int64(0), np.str_('Brasil'): np.int64(1), np.str_('Chile'): np.int64(2)}

In [28]:
%pip install pydantic-settings pandas-profiling

Requirement already satisfied: pydantic-settings in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (2.9.1)
Requirement already satisfied: pandas-profiling in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (3.2.0)
Requirement already satisfied: pydantic>=2.7.0 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from pydantic-settings) (2.11.4)
Requirement already satisfied: python-dotenv>=0.21.0 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from pydantic-settings) (1.1.0)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from pydantic-settings) (0.4.0)
Collecting joblib~=1.1.0 (from pandas-profiling)
  Using cached joblib-1.1.1-py2.py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: scipy>=1.4.1 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from pandas-profiling) (1.15.3)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from pandas-profiling) (2.2.3)
Requirement already satisfied: matplotlib>=3.2.0 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from pandas-profiling) (3.10.1)
Requirement already satisfied: PyYAML>=5.0.0 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from pandas-profiling) (6.0.2)
Requirement already satisfied: jinja2>=2.11.1 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from pandas-profiling) (3.1.6)
Requirement already satisfied: markupsafe~=2.1.1 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from pandas-profiling) (2.1.5)
Requirement already satisfied: visions==0.7.4 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (0.7.4)
Requirement already satisfied: numpy>=1.16.0 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from pandas-profiling) (2.2.5)
Requirement already satisfied: htmlmin>=0.1.12 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from pandas-profiling) (0.1.12)
Requirement already satisfied: missingno>=0.4.2 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from pandas-profiling) (0.5.2)
Requirement already satisfied: phik>=0.11.1 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from pandas-profiling) (0.12.4)
Requirement already satisfied: tangled-up-in-unicode==0.2.0 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from pandas-profiling) (0.2.0)
Requirement already satisfied: requests>=2.24.0 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from pandas-profiling) (2.32.3)
Requirement already satisfied: tqdm>=4.48.2 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from pandas-profiling) (4.67.1)
Requirement already satisfied: seaborn>=0.10.1 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from pandas-profiling) (0.13.2)
Requirement already satisfied: multimethod>=1.4 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from pandas-profiling) (2.0)
Requirement already satisfied: attrs>=19.3.0 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from visions==0.7.4->visions[type_image_path]==0.7.4->pandas-profiling) (25.3.0)
Requirement already satisfied: networkx>=2.4 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from visions==0.7.4->visions[type_image_path]==0.7.4->pandas-profiling) (3.4.2)
Requirement already satisfied: imagehash in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (4.3.2)
Requirement already satisfied: Pillow in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (11.2.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3->pandas-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3->pandas-profiling) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from pydantic>=2.7.0->pydantic-settings) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from pydantic>=2.7.0->pydantic-settings) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from pydantic>=2.7.0->pydantic-settings) (4.13.2)
Requirement already satisfied: six>=1.5 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.2.0->pandas-profiling) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from requests>=2.24.0->pandas-profiling) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from requests>=2.24.0->pandas-profiling) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from requests>=2.24.0->pandas-profiling) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from requests>=2.24.0->pandas-profiling) (2025.4.26)
Requirement already satisfied: colorama in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from tqdm>=4.48.2->pandas-profiling) (0.4.6)
Requirement already satisfied: PyWavelets in c:\users\jesie\onedrive\documentos\jesiel\projetos\curso-ia\.venv\lib\site-packages (from imagehash->visions[type_image_path]==0.7.4->pandas-profiling) (1.8.0)
Using cached joblib-1.1.1-py2.py3-none-any.whl (309 kB)
Installing collected packages: joblib
  Attempting uninstall: joblib
    Found existing installation: joblib 1.5.0
    Uninstalling joblib-1.5.0:
      Successfully uninstalled joblib-1.5.0
Successfully installed joblib-1.1.1
Note: you may need to restart the kernel to use updated packages.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scikit-learn 1.6.1 requires joblib>=1.2.0, but you have joblib 1.1.1 which is incompatible.

In [29]:
import pandas as pd
from pandas_profiling import ProfileReport

df2 = pd.read_excel('dados.xlsx')

# Generate the profile report
doc = ProfileReport(df2, title="Data Analysis Report", minimal=True)

# Save the report to an HTML file
doc.to_file(output_file='analise.html')

c:\Users\jesie\OneDrive\Documentos\jesiel\projetos\Curso-IA\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.11/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.11/u/import-error